version: "3.9"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8081:8080"
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/kry
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
  slow_server:
    build: ./slowserver
    container_name: slow_server
    ports:
      - "8083:3000"
  mysql:
    build: .
    volumes:
      - data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kry
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  data: {}
