const DELETE_RED = '#EA6161'
const KRY_BUTTON_GREEN = '#0A7E85'
const KRY_NAVY_BLUE = '#002845'
const SERVICE_STATUS_OK_GREEN = 'green'
const SERVICE_STATUS_FAIL_RED = '#D8000C'
const WHITE = '#FFF'

export {
  DELETE_RED,
  KRY_BUTTON_GREEN,
  KRY_NAVY_BLUE,
  SERVICE_STATUS_OK_GREEN,
  SERVICE_STATUS_FAIL_RED,
  WHITE,
}
