GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';

CREATE TABLE services (
    id      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name    CHAR(255) NOT NULL,
    url     CHAR(255) NOT NULL,
    status  CHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_name ON services(name);